
// 现在我们只定义了两个actionType;如果我们需要做更多的其他操作时,只需要在这里添加即可
export default {
  // 一般我们的actionType都是长这样的格式
  CART_AMOUNT_INCREASEMENT: "CART_AMOUNT_INCREASEMENT",
  CART_AMOUNT_DECREASEMENT: "CART_AMOUNT_DECREASEMENT",
  // CHANGE_BLOG_LOADING: "CHANGE_BLOG_LOADING"
  /*我们还可以写成下面的这两种的actionType */
  START_FETCH_BLOG_LISTS: "START_FETCH_BLOG_LISTS",//开始请求blog组件的数据
  FETCH_BLOG_LISTS_SUCCESS: "FETCH_BLOG_LISTS_SUCCESS", // 请求成功
  FETCH_BLOG_LISTS_FAIL: "FETCH_BLOG_LISTS_FAIL", // 请求失败
}